// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGPzZXjVIS_EqX_A1qNSqdsIldHM5sVu8',
    appId: '1:775118302580:web:69da7434e50a51758e5021',
    messagingSenderId: '775118302580',
    projectId: 'fireship-quizapp-2a2cb',
    authDomain: 'fireship-quizapp-2a2cb.firebaseapp.com',
    storageBucket: 'fireship-quizapp-2a2cb.appspot.com',
    measurementId: 'G-E539YEKSRQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLN-y3w5ex9PUDpca4MOa4dXVJWgUUN3Q',
    appId: '1:775118302580:android:d7809f4912fc18cc8e5021',
    messagingSenderId: '775118302580',
    projectId: 'fireship-quizapp-2a2cb',
    storageBucket: 'fireship-quizapp-2a2cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4oYIo6ioldDvYifuRqiGyBZ8r-86cbZo',
    appId: '1:775118302580:ios:26571ec3deb03b968e5021',
    messagingSenderId: '775118302580',
    projectId: 'fireship-quizapp-2a2cb',
    storageBucket: 'fireship-quizapp-2a2cb.appspot.com',
    androidClientId: '775118302580-fqptlu0gn1n4flaljskvvnk1mk6g9an4.apps.googleusercontent.com',
    iosClientId: '775118302580-m6361s2v9nl2lkeb2bisdjqf65ggg37p.apps.googleusercontent.com',
    iosBundleId: 'org.ectest.fireshipQuizapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4oYIo6ioldDvYifuRqiGyBZ8r-86cbZo',
    appId: '1:775118302580:ios:26571ec3deb03b968e5021',
    messagingSenderId: '775118302580',
    projectId: 'fireship-quizapp-2a2cb',
    storageBucket: 'fireship-quizapp-2a2cb.appspot.com',
    androidClientId: '775118302580-fqptlu0gn1n4flaljskvvnk1mk6g9an4.apps.googleusercontent.com',
    iosClientId: '775118302580-m6361s2v9nl2lkeb2bisdjqf65ggg37p.apps.googleusercontent.com',
    iosBundleId: 'org.ectest.fireshipQuizapp',
  );
}
